name: robin
channels:
  - defaults
  - conda-forge
  # - pytorch
  # - fastai
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  - scikit-learn
  - statsmodels
  # - sktime
  # - tslearn
  - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  - tensorflow
  - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of robin in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark

# To install the environment:
# conda env create -f environment.yml

# To update the environment:
# conda activate robin
# conda env update --file environment.yml --prune
