market:
- id: 1
  departure_station: '60000'
  arrival_station: '04040'
- id: 2
  departure_station: '04040'
  arrival_station: '71801'
- id: 3
  departure_station: '60000'
  arrival_station: '71801'
userPattern:
- id: 1
  name: Business
  arrival_time: norm
  arrival_time_kwargs:
    loc: 8
    scale: 1
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1.25
  forbidden_departure_hours:
    start: 9
    end: 24
  seats:
  - id: 1
    utility: 10
  - id: 2
    utility: 15
  - id: 3
    utility: 18
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: 0.8
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: 0.7
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: 0.05
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: 0.4
  error: norm
  error_kwargs:
    loc: 2
    scale: 1
- id: 2
  name: Student
  arrival_time: norm
  arrival_time_kwargs:
    loc: 18
    scale: 3
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1
  forbidden_departure_hours:
    start: 6
    end: 14
  seats:
  - id: 1
    utility: 10
  - id: 2
    utility: 12
  - id: 3
    utility: 15
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: 0.1
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: 0.2
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: 0.3
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: 0.3
  error: norm
  error_kwargs:
    loc: 1
    scale: 0.5
- id: 3
  name: Student-Sunday
  arrival_time: norm
  arrival_time_kwargs:
    loc: 18
    scale: 3
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1
  forbidden_departure_hours:
    start: 6
    end: 10
  seats:
  - id: 1
    utility: 10
  - id: 2
    utility: 12
  - id: 3
    utility: 15
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: 0.1
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: 0.2
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: 0.05
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: 0.3
  error: norm
  error_kwargs:
    loc: 1
    scale: 0.5
demandPattern:
- id: 1
  name: Monday-Thursday
  markets:
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: 3500
      high: 5000
    user_pattern_distribution:
    - id: 1
      percentage: 0.8
    - id: 2
      percentage: 0.2
- id: 2
  name: Friday-Saturday
  markets:
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: 5000
      high: 7000
    user_pattern_distribution:
    - id: 1
      percentage: 0.4
    - id: 2
      percentage: 0.6
- id: 3
  name: Sunday
  markets:
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: 5000
      high: 7000
    user_pattern_distribution:
    - id: 1
      percentage: 0.3
    - id: 2
      percentage: 0.1
    - id: 3
      percentage: 0.6
- id: 4
  name: Holiday
  markets:
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: 7000
      high: 9000
    user_pattern_distribution:
    - id: 1
      percentage: 0.3
    - id: 2
      percentage: 0.7
day:
- id: 1
  date: 2023-01-01
  demandPattern: 4
- id: 2
  date: 2023-01-02
  demandPattern: 4
- id: 3
  date: 2023-01-03
  demandPattern: 4
- id: 4
  date: 2023-01-04
  demandPattern: 4
- id: 5
  date: 2023-01-05
  demandPattern: 4
- id: 6
  date: 2023-01-06
  demandPattern: 4
- id: 7
  date: 2023-01-07
  demandPattern: 2
- id: 8
  date: 2023-01-08
  demandPattern: 3
- id: 9
  date: 2023-01-09
  demandPattern: 1
- id: 10
  date: 2023-01-10
  demandPattern: 1
- id: 11
  date: 2023-01-11
  demandPattern: 1
- id: 12
  date: 2023-01-12
  demandPattern: 1
- id: 13
  date: 2023-01-13
  demandPattern: 2
- id: 14
  date: 2023-01-14
  demandPattern: 2
- id: 15
  date: 2023-01-15
  demandPattern: 3
