market:
  - id: 1
    departure_station: '1'
    arrival_station: '4'

userPattern:
  - id: 1
    name: Business
    arrival_time: norm
    arrival_time_kwargs:
      loc: 8
      scale: 1
    purchase_day: randint
    purchase_day_kwargs:
      low: 2
      high: 7
    forbidden_departure_hours:
      start: 9
      end: 24
    seats:
      - id: 1
        utility: 20
    train_service_providers:
      - id: 1
        utility: 3
      - id: 2
        utility: 0
    penalty_arrival_time: polynomial
    penalty_arrival_time_kwargs:
      b_0: 0
      b_1: 1
    penalty_departure_time: polynomial
    penalty_departure_time_kwargs:
      b_0: 0
      b_1: 0.7
    penalty_cost: polynomial
    penalty_cost_kwargs:
      b_0: 0
      b_1: 0.05
    penalty_travel_time: polynomial
    penalty_travel_time_kwargs:
      b_0: 0
      b_1: 0.4
    error: norm
    error_kwargs:
      loc: 4
      scale: 5
  - id: 2
    name: Student
    arrival_time: norm
    arrival_time_kwargs:
      loc: 18
      scale: 3
    purchase_day: randint
    purchase_day_kwargs:
      low: 0
      high: 4
    forbidden_departure_hours:
      start: 6
      end: 14
    seats:
      - id: 1
        utility: 15
    train_service_providers:
      - id: 1
        utility: 1
      - id: 2
        utility: 0
    penalty_arrival_time: polynomial
    penalty_arrival_time_kwargs:
      b_0: 0
      b_1: 0.1
    penalty_departure_time: polynomial
    penalty_departure_time_kwargs:
      b_0: 0
      b_1: 0.2
    penalty_cost: polynomial
    penalty_cost_kwargs:
      b_0: 0
      b_1: 0.4
    penalty_travel_time: polynomial
    penalty_travel_time_kwargs:
      b_0: 0
      b_1: 0.3
    error: norm
    error_kwargs:
      loc: 2
      scale: 10

demandPattern:
  - id: 1
    name: Monday-Thursday
    markets:
      - market: 1
        potential_demand: randint
        potential_demand_kwargs:
          low: 60
          high: 100
        user_pattern_distribution:
          - id: 1
            percentage: 0.7
          - id: 2
            percentage: 0.3

day:
  - id: 1
    date: 2023-09-06
    demandPattern: 1
